import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";

const open_sans = Poppins({ subsets: ["latin"], display: 'swap', weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        <div className="h-screen overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
